
//=======================================================
//  This code is generated by Terasic System Builder
//=======================================================

module DE1_SOC_ADA(

	//////////// ADC //////////
	output		          		ADC_CONVST,
	output		          		ADC_DIN,
	input 		          		ADC_DOUT,
	output		          		ADC_SCLK,

	//////////// Audio //////////
	input 		          		AUD_ADCDAT,
	inout 		          		AUD_ADCLRCK,
	inout 		          		AUD_BCLK,
	output		          		AUD_DACDAT,
	inout 		          		AUD_DACLRCK,
	output		          		AUD_XCK,

	//////////// CLOCK //////////
	input 		          		CLOCK2_50,
	input 		          		CLOCK3_50,
	input 		          		CLOCK4_50,
	input 		          		CLOCK_50,

	//////////// SDRAM //////////
	output		    [12:0]		DRAM_ADDR,
	output		     [1:0]		DRAM_BA,
	output		          		DRAM_CAS_N,
	output		          		DRAM_CKE,
	output		          		DRAM_CLK,
	output		          		DRAM_CS_N,
	inout 		    [15:0]		DRAM_DQ,
	output		          		DRAM_LDQM,
	output		          		DRAM_RAS_N,
	output		          		DRAM_UDQM,
	output		          		DRAM_WE_N,

	//////////// I2C for Audio and Video-In //////////
	output		          		FPGA_I2C_SCLK,
	inout 		          		FPGA_I2C_SDAT,

	//////////// SEG7 //////////
	output		     [6:0]		HEX0,
	output		     [6:0]		HEX1,
	output		     [6:0]		HEX2,
	output		     [6:0]		HEX3,
	output		     [6:0]		HEX4,
	output		     [6:0]		HEX5,

	//////////// IR //////////
	input 		          		IRDA_RXD,
	output		          		IRDA_TXD,

	//////////// KEY //////////
	input 		     [3:0]		KEY,

	//////////// LED //////////
	output		     [9:0]		LEDR,

	//////////// PS2 //////////
	inout 		          		PS2_CLK,
	inout 		          		PS2_CLK2,
	inout 		          		PS2_DAT,
	inout 		          		PS2_DAT2,

	//////////// SW //////////
	input 		     [9:0]		SW,

	//////////// Video-In //////////
	input 		          		TD_CLK27,
	input 		     [7:0]		TD_DATA,
	input 		          		TD_HS,
	output		          		TD_RESET_N,
	input 		          		TD_VS,

	//////////// VGA //////////
	output		          		VGA_BLANK_N,
	output		     [7:0]		VGA_B,
	output		          		VGA_CLK,
	output		     [7:0]		VGA_G,
	output		          		VGA_HS,
	output		     [7:0]		VGA_R,
	output		          		VGA_SYNC_N,
	output		          		VGA_VS,

	//////////// GPIO_0_1, GPIO_0_1 connect to ADA - High Speed ADC/DAC //////////
	output		          		ADC_CLK_A,
	output		          		ADC_CLK_B,
	input 		    [13:0]		ADC_DA,
	input 		    [13:0]		ADC_DB,
	output		          		ADC_OEB_A,
	output		          		ADC_OEB_B,
	input 		          		ADC_OTR_A,
	input 		          		ADC_OTR_B,
	output		          		DAC_CLK_A,
	output		          		DAC_CLK_B,
	output		    [13:0]		DAC_DA,
	output		    [13:0]		DAC_DB,
	output		          		DAC_MODE,
	output		          		DAC_WRT_A,
	output		          		DAC_WRT_B,
	input 		          		OSC_SMA_ADC4,
	output		          		POWER_ON,
	input 		          		SMA_DAC4
);



//=======================================================
//  REG/WIRE declarations
//=======================================================

DE1_SoC_ADDA_TOP       U1  (
                        .CLOCK_50	 (CLOCK_50),
                        .ADC_CLK_A	 (ADC_CLK_A),
								.ADC_CLK_B   (ADC_CLK_B),
								.ADC_DA		 (ADC_DA),
								.ADC_DB		 (ADC_DB),
								.ADC_OEB_A	 (ADC_OEB_A),
								.ADC_OEB_B	 (ADC_OEB_B),
								.ADC_OTR_A   (ADC_OTR_A),
								.ADC_OTR_B	 (ADC_OTR_B),
								.DAC_CLK_A	 (DAC_CLK_A),
								.DAC_CLK_B   (DAC_CLK_B),
								.DAC_DA		 (DAC_DA),
								.DAC_DB		 (DAC_DB),
								.DAC_MODE	 (DAC_MODE),
								.DAC_WRT_A	 (DAC_WRT_A),
								.DAC_WRT_B	 (DAC_WRT_B),
								.POWER_ON    (POWER_ON),
								.OSC_SMA_ADC4(OSC_SMA_ADC4),
							   .SMA_DAC4    (SMA_DAC4)
                        );



endmodule
