	soc_system u0 (
		.clk_clk                           (<connected-to-clk_clk>),                           //                clk.clk
		.clk_1m_clk                        (<connected-to-clk_1m_clk>),                        //             clk_1m.clk
		.ctrl_rx_reset_reset_n             (<connected-to-ctrl_rx_reset_reset_n>),             //      ctrl_rx_reset.reset_n
		.ctrl_rx_writeclk_clk              (<connected-to-ctrl_rx_writeclk_clk>),              //   ctrl_rx_writeclk.clk
		.ctrl_rx_writecsr_address          (<connected-to-ctrl_rx_writecsr_address>),          //   ctrl_rx_writecsr.address
		.ctrl_rx_writecsr_read             (<connected-to-ctrl_rx_writecsr_read>),             //                   .read
		.ctrl_rx_writecsr_writedata        (<connected-to-ctrl_rx_writecsr_writedata>),        //                   .writedata
		.ctrl_rx_writecsr_write            (<connected-to-ctrl_rx_writecsr_write>),            //                   .write
		.ctrl_rx_writecsr_readdata         (<connected-to-ctrl_rx_writecsr_readdata>),         //                   .readdata
		.ctrl_rx_writedata_writedata       (<connected-to-ctrl_rx_writedata_writedata>),       //  ctrl_rx_writedata.writedata
		.ctrl_rx_writedata_write           (<connected-to-ctrl_rx_writedata_write>),           //                   .write
		.ctrl_tx_readclk_clk               (<connected-to-ctrl_tx_readclk_clk>),               //    ctrl_tx_readclk.clk
		.ctrl_tx_readcsr_address           (<connected-to-ctrl_tx_readcsr_address>),           //    ctrl_tx_readcsr.address
		.ctrl_tx_readcsr_read              (<connected-to-ctrl_tx_readcsr_read>),              //                   .read
		.ctrl_tx_readcsr_writedata         (<connected-to-ctrl_tx_readcsr_writedata>),         //                   .writedata
		.ctrl_tx_readcsr_write             (<connected-to-ctrl_tx_readcsr_write>),             //                   .write
		.ctrl_tx_readcsr_readdata          (<connected-to-ctrl_tx_readcsr_readdata>),          //                   .readdata
		.ctrl_tx_readdata_readdata         (<connected-to-ctrl_tx_readdata_readdata>),         //   ctrl_tx_readdata.readdata
		.ctrl_tx_readdata_read             (<connected-to-ctrl_tx_readdata_read>),             //                   .read
		.ctrl_tx_reset_reset_n             (<connected-to-ctrl_tx_reset_reset_n>),             //      ctrl_tx_reset.reset_n
		.hps_0_ddr_mem_a                   (<connected-to-hps_0_ddr_mem_a>),                   //          hps_0_ddr.mem_a
		.hps_0_ddr_mem_ba                  (<connected-to-hps_0_ddr_mem_ba>),                  //                   .mem_ba
		.hps_0_ddr_mem_ck                  (<connected-to-hps_0_ddr_mem_ck>),                  //                   .mem_ck
		.hps_0_ddr_mem_ck_n                (<connected-to-hps_0_ddr_mem_ck_n>),                //                   .mem_ck_n
		.hps_0_ddr_mem_cke                 (<connected-to-hps_0_ddr_mem_cke>),                 //                   .mem_cke
		.hps_0_ddr_mem_cs_n                (<connected-to-hps_0_ddr_mem_cs_n>),                //                   .mem_cs_n
		.hps_0_ddr_mem_ras_n               (<connected-to-hps_0_ddr_mem_ras_n>),               //                   .mem_ras_n
		.hps_0_ddr_mem_cas_n               (<connected-to-hps_0_ddr_mem_cas_n>),               //                   .mem_cas_n
		.hps_0_ddr_mem_we_n                (<connected-to-hps_0_ddr_mem_we_n>),                //                   .mem_we_n
		.hps_0_ddr_mem_reset_n             (<connected-to-hps_0_ddr_mem_reset_n>),             //                   .mem_reset_n
		.hps_0_ddr_mem_dq                  (<connected-to-hps_0_ddr_mem_dq>),                  //                   .mem_dq
		.hps_0_ddr_mem_dqs                 (<connected-to-hps_0_ddr_mem_dqs>),                 //                   .mem_dqs
		.hps_0_ddr_mem_dqs_n               (<connected-to-hps_0_ddr_mem_dqs_n>),               //                   .mem_dqs_n
		.hps_0_ddr_mem_odt                 (<connected-to-hps_0_ddr_mem_odt>),                 //                   .mem_odt
		.hps_0_ddr_mem_dm                  (<connected-to-hps_0_ddr_mem_dm>),                  //                   .mem_dm
		.hps_0_ddr_oct_rzqin               (<connected-to-hps_0_ddr_oct_rzqin>),               //                   .oct_rzqin
		.hps_0_io_hps_io_emac1_inst_TX_CLK (<connected-to-hps_0_io_hps_io_emac1_inst_TX_CLK>), //           hps_0_io.hps_io_emac1_inst_TX_CLK
		.hps_0_io_hps_io_emac1_inst_TXD0   (<connected-to-hps_0_io_hps_io_emac1_inst_TXD0>),   //                   .hps_io_emac1_inst_TXD0
		.hps_0_io_hps_io_emac1_inst_TXD1   (<connected-to-hps_0_io_hps_io_emac1_inst_TXD1>),   //                   .hps_io_emac1_inst_TXD1
		.hps_0_io_hps_io_emac1_inst_TXD2   (<connected-to-hps_0_io_hps_io_emac1_inst_TXD2>),   //                   .hps_io_emac1_inst_TXD2
		.hps_0_io_hps_io_emac1_inst_TXD3   (<connected-to-hps_0_io_hps_io_emac1_inst_TXD3>),   //                   .hps_io_emac1_inst_TXD3
		.hps_0_io_hps_io_emac1_inst_RXD0   (<connected-to-hps_0_io_hps_io_emac1_inst_RXD0>),   //                   .hps_io_emac1_inst_RXD0
		.hps_0_io_hps_io_emac1_inst_MDIO   (<connected-to-hps_0_io_hps_io_emac1_inst_MDIO>),   //                   .hps_io_emac1_inst_MDIO
		.hps_0_io_hps_io_emac1_inst_MDC    (<connected-to-hps_0_io_hps_io_emac1_inst_MDC>),    //                   .hps_io_emac1_inst_MDC
		.hps_0_io_hps_io_emac1_inst_RX_CTL (<connected-to-hps_0_io_hps_io_emac1_inst_RX_CTL>), //                   .hps_io_emac1_inst_RX_CTL
		.hps_0_io_hps_io_emac1_inst_TX_CTL (<connected-to-hps_0_io_hps_io_emac1_inst_TX_CTL>), //                   .hps_io_emac1_inst_TX_CTL
		.hps_0_io_hps_io_emac1_inst_RX_CLK (<connected-to-hps_0_io_hps_io_emac1_inst_RX_CLK>), //                   .hps_io_emac1_inst_RX_CLK
		.hps_0_io_hps_io_emac1_inst_RXD1   (<connected-to-hps_0_io_hps_io_emac1_inst_RXD1>),   //                   .hps_io_emac1_inst_RXD1
		.hps_0_io_hps_io_emac1_inst_RXD2   (<connected-to-hps_0_io_hps_io_emac1_inst_RXD2>),   //                   .hps_io_emac1_inst_RXD2
		.hps_0_io_hps_io_emac1_inst_RXD3   (<connected-to-hps_0_io_hps_io_emac1_inst_RXD3>),   //                   .hps_io_emac1_inst_RXD3
		.hps_0_io_hps_io_qspi_inst_IO0     (<connected-to-hps_0_io_hps_io_qspi_inst_IO0>),     //                   .hps_io_qspi_inst_IO0
		.hps_0_io_hps_io_qspi_inst_IO1     (<connected-to-hps_0_io_hps_io_qspi_inst_IO1>),     //                   .hps_io_qspi_inst_IO1
		.hps_0_io_hps_io_qspi_inst_IO2     (<connected-to-hps_0_io_hps_io_qspi_inst_IO2>),     //                   .hps_io_qspi_inst_IO2
		.hps_0_io_hps_io_qspi_inst_IO3     (<connected-to-hps_0_io_hps_io_qspi_inst_IO3>),     //                   .hps_io_qspi_inst_IO3
		.hps_0_io_hps_io_qspi_inst_SS0     (<connected-to-hps_0_io_hps_io_qspi_inst_SS0>),     //                   .hps_io_qspi_inst_SS0
		.hps_0_io_hps_io_qspi_inst_CLK     (<connected-to-hps_0_io_hps_io_qspi_inst_CLK>),     //                   .hps_io_qspi_inst_CLK
		.hps_0_io_hps_io_sdio_inst_CMD     (<connected-to-hps_0_io_hps_io_sdio_inst_CMD>),     //                   .hps_io_sdio_inst_CMD
		.hps_0_io_hps_io_sdio_inst_D0      (<connected-to-hps_0_io_hps_io_sdio_inst_D0>),      //                   .hps_io_sdio_inst_D0
		.hps_0_io_hps_io_sdio_inst_D1      (<connected-to-hps_0_io_hps_io_sdio_inst_D1>),      //                   .hps_io_sdio_inst_D1
		.hps_0_io_hps_io_sdio_inst_CLK     (<connected-to-hps_0_io_hps_io_sdio_inst_CLK>),     //                   .hps_io_sdio_inst_CLK
		.hps_0_io_hps_io_sdio_inst_D2      (<connected-to-hps_0_io_hps_io_sdio_inst_D2>),      //                   .hps_io_sdio_inst_D2
		.hps_0_io_hps_io_sdio_inst_D3      (<connected-to-hps_0_io_hps_io_sdio_inst_D3>),      //                   .hps_io_sdio_inst_D3
		.hps_0_io_hps_io_usb1_inst_D0      (<connected-to-hps_0_io_hps_io_usb1_inst_D0>),      //                   .hps_io_usb1_inst_D0
		.hps_0_io_hps_io_usb1_inst_D1      (<connected-to-hps_0_io_hps_io_usb1_inst_D1>),      //                   .hps_io_usb1_inst_D1
		.hps_0_io_hps_io_usb1_inst_D2      (<connected-to-hps_0_io_hps_io_usb1_inst_D2>),      //                   .hps_io_usb1_inst_D2
		.hps_0_io_hps_io_usb1_inst_D3      (<connected-to-hps_0_io_hps_io_usb1_inst_D3>),      //                   .hps_io_usb1_inst_D3
		.hps_0_io_hps_io_usb1_inst_D4      (<connected-to-hps_0_io_hps_io_usb1_inst_D4>),      //                   .hps_io_usb1_inst_D4
		.hps_0_io_hps_io_usb1_inst_D5      (<connected-to-hps_0_io_hps_io_usb1_inst_D5>),      //                   .hps_io_usb1_inst_D5
		.hps_0_io_hps_io_usb1_inst_D6      (<connected-to-hps_0_io_hps_io_usb1_inst_D6>),      //                   .hps_io_usb1_inst_D6
		.hps_0_io_hps_io_usb1_inst_D7      (<connected-to-hps_0_io_hps_io_usb1_inst_D7>),      //                   .hps_io_usb1_inst_D7
		.hps_0_io_hps_io_usb1_inst_CLK     (<connected-to-hps_0_io_hps_io_usb1_inst_CLK>),     //                   .hps_io_usb1_inst_CLK
		.hps_0_io_hps_io_usb1_inst_STP     (<connected-to-hps_0_io_hps_io_usb1_inst_STP>),     //                   .hps_io_usb1_inst_STP
		.hps_0_io_hps_io_usb1_inst_DIR     (<connected-to-hps_0_io_hps_io_usb1_inst_DIR>),     //                   .hps_io_usb1_inst_DIR
		.hps_0_io_hps_io_usb1_inst_NXT     (<connected-to-hps_0_io_hps_io_usb1_inst_NXT>),     //                   .hps_io_usb1_inst_NXT
		.hps_0_io_hps_io_spim1_inst_CLK    (<connected-to-hps_0_io_hps_io_spim1_inst_CLK>),    //                   .hps_io_spim1_inst_CLK
		.hps_0_io_hps_io_spim1_inst_MOSI   (<connected-to-hps_0_io_hps_io_spim1_inst_MOSI>),   //                   .hps_io_spim1_inst_MOSI
		.hps_0_io_hps_io_spim1_inst_MISO   (<connected-to-hps_0_io_hps_io_spim1_inst_MISO>),   //                   .hps_io_spim1_inst_MISO
		.hps_0_io_hps_io_spim1_inst_SS0    (<connected-to-hps_0_io_hps_io_spim1_inst_SS0>),    //                   .hps_io_spim1_inst_SS0
		.hps_0_io_hps_io_uart0_inst_RX     (<connected-to-hps_0_io_hps_io_uart0_inst_RX>),     //                   .hps_io_uart0_inst_RX
		.hps_0_io_hps_io_uart0_inst_TX     (<connected-to-hps_0_io_hps_io_uart0_inst_TX>),     //                   .hps_io_uart0_inst_TX
		.hps_0_io_hps_io_i2c0_inst_SDA     (<connected-to-hps_0_io_hps_io_i2c0_inst_SDA>),     //                   .hps_io_i2c0_inst_SDA
		.hps_0_io_hps_io_i2c0_inst_SCL     (<connected-to-hps_0_io_hps_io_i2c0_inst_SCL>),     //                   .hps_io_i2c0_inst_SCL
		.hps_0_io_hps_io_i2c1_inst_SDA     (<connected-to-hps_0_io_hps_io_i2c1_inst_SDA>),     //                   .hps_io_i2c1_inst_SDA
		.hps_0_io_hps_io_i2c1_inst_SCL     (<connected-to-hps_0_io_hps_io_i2c1_inst_SCL>),     //                   .hps_io_i2c1_inst_SCL
		.hps_0_io_hps_io_gpio_inst_GPIO09  (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO09>),  //                   .hps_io_gpio_inst_GPIO09
		.hps_0_io_hps_io_gpio_inst_GPIO35  (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO35>),  //                   .hps_io_gpio_inst_GPIO35
		.hps_0_io_hps_io_gpio_inst_GPIO40  (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO40>),  //                   .hps_io_gpio_inst_GPIO40
		.hps_0_io_hps_io_gpio_inst_GPIO48  (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO48>),  //                   .hps_io_gpio_inst_GPIO48
		.hps_0_io_hps_io_gpio_inst_GPIO53  (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO53>),  //                   .hps_io_gpio_inst_GPIO53
		.hps_0_io_hps_io_gpio_inst_GPIO54  (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO54>),  //                   .hps_io_gpio_inst_GPIO54
		.hps_0_io_hps_io_gpio_inst_GPIO61  (<connected-to-hps_0_io_hps_io_gpio_inst_GPIO61>),  //                   .hps_io_gpio_inst_GPIO61
		.reset_reset_n                     (<connected-to-reset_reset_n>),                     //              reset.reset_n
		.rx_video_reset_reset_n            (<connected-to-rx_video_reset_reset_n>),            //     rx_video_reset.reset_n
		.rx_video_writeclk_clk             (<connected-to-rx_video_writeclk_clk>),             //  rx_video_writeclk.clk
		.rx_video_writecsr_address         (<connected-to-rx_video_writecsr_address>),         //  rx_video_writecsr.address
		.rx_video_writecsr_read            (<connected-to-rx_video_writecsr_read>),            //                   .read
		.rx_video_writecsr_writedata       (<connected-to-rx_video_writecsr_writedata>),       //                   .writedata
		.rx_video_writecsr_write           (<connected-to-rx_video_writecsr_write>),           //                   .write
		.rx_video_writecsr_readdata        (<connected-to-rx_video_writecsr_readdata>),        //                   .readdata
		.rx_video_writedata_writedata      (<connected-to-rx_video_writedata_writedata>),      // rx_video_writedata.writedata
		.rx_video_writedata_write          (<connected-to-rx_video_writedata_write>),          //                   .write
		.tx_video_readclk_clk              (<connected-to-tx_video_readclk_clk>),              //   tx_video_readclk.clk
		.tx_video_readcsr_address          (<connected-to-tx_video_readcsr_address>),          //   tx_video_readcsr.address
		.tx_video_readcsr_read             (<connected-to-tx_video_readcsr_read>),             //                   .read
		.tx_video_readcsr_writedata        (<connected-to-tx_video_readcsr_writedata>),        //                   .writedata
		.tx_video_readcsr_write            (<connected-to-tx_video_readcsr_write>),            //                   .write
		.tx_video_readcsr_readdata         (<connected-to-tx_video_readcsr_readdata>),         //                   .readdata
		.tx_video_readdata_readdata        (<connected-to-tx_video_readdata_readdata>),        //  tx_video_readdata.readdata
		.tx_video_readdata_read            (<connected-to-tx_video_readdata_read>),            //                   .read
		.tx_video_reset_reset_n            (<connected-to-tx_video_reset_reset_n>),            //     tx_video_reset.reset_n
		.leds_out_export                   (<connected-to-leds_out_export>),                   //           leds_out.export
		.switches_in_export                (<connected-to-switches_in_export>)                 //        switches_in.export
	);

